### ISSUE TITLE
添加基于XML数据格式的支持

### ISSUE THREAD

**Issue by uzilla** [urain39/KngetPy#18]
如题。

**Comment by urain39** [comment]
目前没办法适配所有的api链接格式，但是大部分的核心代码都可以复用，所以我需要花点时间再想想怎么去适配链接格式。就目前来看，使用其他项目中的模块化设计可能会更好一些。

**Comment by urain39** [comment]
我自己的有两套方案：1. 单独适配基于原版danbooru(即使用xml元数据的网站)，新建一个子模块(非repo) 2. 在现有的项目上直接支持已有的格式，并在配置中标注网站类型(默认moebooru)。

我认为两种方案都很好，所以可以将两个方案合成一个最终的解决方案。

**Comment by urain39** [comment]
目前没办法适配所有的api链接格式，但是大部分的核心代码都可以复用，所以我需要花点时间再想想怎么去适配链接格式。就目前来看，使用其他项目中的模块化设计可能会更好一些。

**Comment by urain39** [comment]
已放弃适配XML格式
